server:
  port: 8700
spring:
  kafka:
    producer:
      bootstrap-servers: 172.18.0.1:29092
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: json-consumer

logging:
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(%logger{0}){blue} %clr(%m){yellow}%n"
